# Form implementation generated from reading ui file 'apt.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormApt(object):
    def setupUi(self, FormApt):
        FormApt.setObjectName("FormApt")
        FormApt.resize(614, 450)
        FormApt.setMinimumSize(QtCore.QSize(450, 450))
        self.gridLayout = QtWidgets.QGridLayout(FormApt)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidgetPackages = QtWidgets.QTreeWidget(parent=FormApt)
        self.treeWidgetPackages.setObjectName("treeWidgetPackages")
        self.gridLayout.addWidget(self.treeWidgetPackages, 1, 0, 1, 4)
        self.progressBar = QtWidgets.QProgressBar(parent=FormApt)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 3)
        self.lineEditSearch = QtWidgets.QLineEdit(parent=FormApt)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.gridLayout.addWidget(self.lineEditSearch, 0, 0, 1, 4)
        self.pushButtonNext = QtWidgets.QPushButton(parent=FormApt)
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.gridLayout.addWidget(self.pushButtonNext, 2, 3, 1, 1)
        self.pushButtonPrevious = QtWidgets.QPushButton(parent=FormApt)
        self.pushButtonPrevious.setObjectName("pushButtonPrevious")
        self.gridLayout.addWidget(self.pushButtonPrevious, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=FormApt)
        self.label.setMinimumSize(QtCore.QSize(81, 20))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 2, 1, 1)
        self.pushButtonRefresh = QtWidgets.QPushButton(parent=FormApt)
        self.pushButtonRefresh.setMinimumSize(QtCore.QSize(88, 34))
        self.pushButtonRefresh.setMaximumSize(QtCore.QSize(88, 34))
        self.pushButtonRefresh.setObjectName("pushButtonRefresh")
        self.gridLayout.addWidget(self.pushButtonRefresh, 3, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(328, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)

        self.retranslateUi(FormApt)
        QtCore.QMetaObject.connectSlotsByName(FormApt)

    def retranslateUi(self, FormApt):
        _translate = QtCore.QCoreApplication.translate
        FormApt.setWindowTitle(_translate("FormApt", "Apt"))
        self.treeWidgetPackages.headerItem().setText(0, _translate("FormApt", "Package"))
        self.treeWidgetPackages.headerItem().setText(1, _translate("FormApt", "Version"))
        self.treeWidgetPackages.headerItem().setText(2, _translate("FormApt", "Tags"))
        self.treeWidgetPackages.headerItem().setText(3, _translate("FormApt", "Arch"))
        self.treeWidgetPackages.headerItem().setText(4, _translate("FormApt", "Repo"))
        self.lineEditSearch.setPlaceholderText(_translate("FormApt", "Search Packages"))
        self.pushButtonNext.setText(_translate("FormApt", "Next"))
        self.pushButtonPrevious.setText(_translate("FormApt", "Previous"))
        self.label.setText(_translate("FormApt", "1 of 1000"))
        self.pushButtonRefresh.setText(_translate("FormApt", "Refresh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormApt = QtWidgets.QWidget()
    ui = Ui_FormApt()
    ui.setupUi(FormApt)
    FormApt.show()
    sys.exit(app.exec())
