# Form implementation generated from reading ui file 'cl.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormCL(object):
    def setupUi(self, FormCL):
        FormCL.setObjectName("FormCL")
        FormCL.resize(450, 450)
        FormCL.setMinimumSize(QtCore.QSize(450, 450))
        self.gridLayout = QtWidgets.QGridLayout(FormCL)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditSearch = QtWidgets.QLineEdit(parent=FormCL)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.gridLayout.addWidget(self.lineEditSearch, 0, 0, 1, 2)
        self.treeWidgetOutput = QtWidgets.QTreeWidget(parent=FormCL)
        self.treeWidgetOutput.setObjectName("treeWidgetOutput")
        self.gridLayout.addWidget(self.treeWidgetOutput, 1, 0, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(parent=FormCL)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 0, 1, 2)
        self.line = QtWidgets.QFrame(parent=FormCL)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 2)
        self.comboBox = QtWidgets.QComboBox(parent=FormCL)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 4, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=FormCL)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lineEdit.setFont(font)
        self.lineEdit.setFrame(False)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 4, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(parent=FormCL)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 5, 0, 1, 2)

        self.retranslateUi(FormCL)
        QtCore.QMetaObject.connectSlotsByName(FormCL)

    def retranslateUi(self, FormCL):
        _translate = QtCore.QCoreApplication.translate
        FormCL.setWindowTitle(_translate("FormCL", "Command Line"))
        self.lineEditSearch.setPlaceholderText(_translate("FormCL", "Search History"))
        self.treeWidgetOutput.headerItem().setText(0, _translate("FormCL", "Machine"))
        self.treeWidgetOutput.headerItem().setText(1, _translate("FormCL", "Output"))
        self.comboBox.setItemText(0, _translate("FormCL", "$"))
        self.comboBox.setItemText(1, _translate("FormCL", "$ sudo"))
        self.lineEdit.setPlaceholderText(_translate("FormCL", "Command"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormCL = QtWidgets.QWidget()
    ui = Ui_FormCL()
    ui.setupUi(FormCL)
    FormCL.show()
    sys.exit(app.exec())
