# Form implementation generated from reading ui file 'license.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormLicense(object):
    def setupUi(self, FormLicense):
        FormLicense.setObjectName("FormLicense")
        FormLicense.resize(450, 450)
        FormLicense.setMinimumSize(QtCore.QSize(450, 450))
        self.gridLayout = QtWidgets.QGridLayout(FormLicense)
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=FormLicense)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 0, 0, 1, 1)

        self.retranslateUi(FormLicense)
        QtCore.QMetaObject.connectSlotsByName(FormLicense)

    def retranslateUi(self, FormLicense):
        _translate = QtCore.QCoreApplication.translate
        FormLicense.setWindowTitle(_translate("FormLicense", "License"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormLicense = QtWidgets.QWidget()
    ui = Ui_FormLicense()
    ui.setupUi(FormLicense)
    FormLicense.show()
    sys.exit(app.exec())
