# Form implementation generated from reading ui file 'logs.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormLogs(object):
    def setupUi(self, FormLogs):
        FormLogs.setObjectName("FormLogs")
        FormLogs.resize(450, 450)
        FormLogs.setMinimumSize(QtCore.QSize(450, 450))
        self.gridLayout = QtWidgets.QGridLayout(FormLogs)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditSearch = QtWidgets.QLineEdit(parent=FormLogs)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.gridLayout.addWidget(self.lineEditSearch, 0, 0, 1, 4)
        self.listWidget = QtWidgets.QListWidget(parent=FormLogs)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 1, 0, 1, 4)
        self.label = QtWidgets.QLabel(parent=FormLogs)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.pushButtonReload = QtWidgets.QPushButton(parent=FormLogs)
        self.pushButtonReload.setMinimumSize(QtCore.QSize(84, 34))
        self.pushButtonReload.setMaximumSize(QtCore.QSize(84, 34))
        self.pushButtonReload.setObjectName("pushButtonReload")
        self.gridLayout.addWidget(self.pushButtonReload, 2, 1, 1, 1)
        self.pushButtonClear = QtWidgets.QPushButton(parent=FormLogs)
        self.pushButtonClear.setMinimumSize(QtCore.QSize(84, 34))
        self.pushButtonClear.setMaximumSize(QtCore.QSize(84, 34))
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.gridLayout.addWidget(self.pushButtonClear, 2, 2, 1, 1)
        self.pushButtonExport = QtWidgets.QPushButton(parent=FormLogs)
        self.pushButtonExport.setMinimumSize(QtCore.QSize(84, 34))
        self.pushButtonExport.setMaximumSize(QtCore.QSize(84, 34))
        self.pushButtonExport.setObjectName("pushButtonExport")
        self.gridLayout.addWidget(self.pushButtonExport, 2, 3, 1, 1)

        self.retranslateUi(FormLogs)
        QtCore.QMetaObject.connectSlotsByName(FormLogs)

    def retranslateUi(self, FormLogs):
        _translate = QtCore.QCoreApplication.translate
        FormLogs.setWindowTitle(_translate("FormLogs", "Logs"))
        self.lineEditSearch.setPlaceholderText(_translate("FormLogs", "Search logs"))
        self.label.setText(_translate("FormLogs", "TextLabel"))
        self.pushButtonReload.setText(_translate("FormLogs", "Reload"))
        self.pushButtonClear.setText(_translate("FormLogs", "Clear"))
        self.pushButtonExport.setText(_translate("FormLogs", "Export"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormLogs = QtWidgets.QWidget()
    ui = Ui_FormLogs()
    ui.setupUi(FormLogs)
    FormLogs.show()
    sys.exit(app.exec())
