# Form implementation generated from reading ui file 'package_info.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormShowPackage(object):
    def setupUi(self, FormShowPackage):
        FormShowPackage.setObjectName("FormShowPackage")
        FormShowPackage.resize(450, 450)
        FormShowPackage.setMinimumSize(QtCore.QSize(450, 450))
        self.gridLayout = QtWidgets.QGridLayout(FormShowPackage)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=FormShowPackage)
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(FormShowPackage)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(FormShowPackage)

    def retranslateUi(self, FormShowPackage):
        _translate = QtCore.QCoreApplication.translate
        FormShowPackage.setWindowTitle(_translate("FormShowPackage", "Package Information"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormShowPackage = QtWidgets.QWidget()
    ui = Ui_FormShowPackage()
    ui.setupUi(FormShowPackage)
    FormShowPackage.show()
    sys.exit(app.exec())
