# Form implementation generated from reading ui file 'remote_logs.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormRemoteLogs(object):
    def setupUi(self, FormRemoteLogs):
        FormRemoteLogs.setObjectName("FormRemoteLogs")
        FormRemoteLogs.resize(450, 450)
        FormRemoteLogs.setMinimumSize(QtCore.QSize(450, 450))
        self.gridLayout = QtWidgets.QGridLayout(FormRemoteLogs)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditSearch = QtWidgets.QLineEdit(parent=FormRemoteLogs)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.gridLayout.addWidget(self.lineEditSearch, 0, 0, 1, 1)
        self.tabWidgetLogs = QtWidgets.QTabWidget(parent=FormRemoteLogs)
        self.tabWidgetLogs.setObjectName("tabWidgetLogs")
        self.gridLayout.addWidget(self.tabWidgetLogs, 1, 0, 1, 1)

        self.retranslateUi(FormRemoteLogs)
        self.tabWidgetLogs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(FormRemoteLogs)

    def retranslateUi(self, FormRemoteLogs):
        _translate = QtCore.QCoreApplication.translate
        FormRemoteLogs.setWindowTitle(_translate("FormRemoteLogs", "Remote Logs"))
        self.lineEditSearch.setPlaceholderText(_translate("FormRemoteLogs", "Search Logs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormRemoteLogs = QtWidgets.QWidget()
    ui = Ui_FormRemoteLogs()
    ui.setupUi(FormRemoteLogs)
    FormRemoteLogs.show()
    sys.exit(app.exec())
