# Form implementation generated from reading ui file 'services.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormServices(object):
    def setupUi(self, FormServices):
        FormServices.setObjectName("FormServices")
        FormServices.resize(616, 450)
        FormServices.setMinimumSize(QtCore.QSize(450, 450))
        self.gridLayout = QtWidgets.QGridLayout(FormServices)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditSearch = QtWidgets.QLineEdit(parent=FormServices)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.gridLayout.addWidget(self.lineEditSearch, 0, 0, 1, 2)
        self.treeWidgetServices = QtWidgets.QTreeWidget(parent=FormServices)
        self.treeWidgetServices.setObjectName("treeWidgetServices")
        self.gridLayout.addWidget(self.treeWidgetServices, 1, 0, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(parent=FormServices)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 0, 1, 1)
        self.pushButtonRefresh = QtWidgets.QPushButton(parent=FormServices)
        self.pushButtonRefresh.setMinimumSize(QtCore.QSize(88, 34))
        self.pushButtonRefresh.setMaximumSize(QtCore.QSize(88, 34))
        self.pushButtonRefresh.setObjectName("pushButtonRefresh")
        self.gridLayout.addWidget(self.pushButtonRefresh, 2, 1, 1, 1)

        self.retranslateUi(FormServices)
        QtCore.QMetaObject.connectSlotsByName(FormServices)

    def retranslateUi(self, FormServices):
        _translate = QtCore.QCoreApplication.translate
        FormServices.setWindowTitle(_translate("FormServices", "Services"))
        self.lineEditSearch.setPlaceholderText(_translate("FormServices", "Search Services"))
        self.treeWidgetServices.headerItem().setText(0, _translate("FormServices", "Machine"))
        self.treeWidgetServices.headerItem().setText(1, _translate("FormServices", "Load"))
        self.treeWidgetServices.headerItem().setText(2, _translate("FormServices", "Active"))
        self.treeWidgetServices.headerItem().setText(3, _translate("FormServices", "Substate"))
        self.treeWidgetServices.headerItem().setText(4, _translate("FormServices", "Description"))
        self.pushButtonRefresh.setText(_translate("FormServices", "Refresh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormServices = QtWidgets.QWidget()
    ui = Ui_FormServices()
    ui.setupUi(FormServices)
    FormServices.show()
    sys.exit(app.exec())
