# Form implementation generated from reading ui file 'user.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormUser(object):
    def setupUi(self, FormUser):
        FormUser.setObjectName("FormUser")
        FormUser.resize(450, 450)
        FormUser.setMinimumSize(QtCore.QSize(450, 450))
        self.gridLayout = QtWidgets.QGridLayout(FormUser)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonReload = QtWidgets.QPushButton(parent=FormUser)
        self.pushButtonReload.setMinimumSize(QtCore.QSize(88, 34))
        self.pushButtonReload.setMaximumSize(QtCore.QSize(88, 34))
        self.pushButtonReload.setObjectName("pushButtonReload")
        self.gridLayout.addWidget(self.pushButtonReload, 2, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(parent=FormUser)
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(parent=FormUser)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)

        self.retranslateUi(FormUser)
        QtCore.QMetaObject.connectSlotsByName(FormUser)

    def retranslateUi(self, FormUser):
        _translate = QtCore.QCoreApplication.translate
        FormUser.setWindowTitle(_translate("FormUser", "Users"))
        self.pushButtonReload.setText(_translate("FormUser", "Reload"))
        self.lineEdit.setPlaceholderText(_translate("FormUser", "Search Users"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormUser = QtWidgets.QWidget()
    ui = Ui_FormUser()
    ui.setupUi(FormUser)
    FormUser.show()
    sys.exit(app.exec())
